name: Deploy to Linode

on:
  push:
    branches: [ main ]  # 當 main 分支有推送時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/poker-hand-note
            git pull origin main
            npm install --production
            rm -rf .next    # 清除舊的構建文件
            npm run build
            if [ ! -d ".next" ]; then
              echo "Build failed: .next directory not found"
              exit 1
            fi
            pm2 restart poker-hand-note