name: Deploy to Linode
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/poker-hand-note
            echo "Pulling latest changes..."
            git pull origin main || exit 1
            
            echo "Installing dependencies..."
            npm install || exit 1
            
            echo "Building application..."
            npm run build || exit 1
            
            echo "Restarting PM2..."
            pm2 restart poker-hand-note || exit 1
            
            echo "Deployment completed successfully"